name: Build Executable

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10"]
        arch: [amd64, arm64]
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build single executable
        run: |
          pyinstaller --onefile --name ytmusic-sync ytmusic-sync.py
          # Ensure `main.py` imports any other Python files in your program.

      - name: Upload executable
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}--${{ matrix.arch }}-ytmusic-sync
          path: dist/ytmusic-sync*
