name: Build Executable

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.10]  # Only Python 3.10
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build single executable
        run: |
          pyinstaller --onefile --name ytmusic-sync main.py
          # Ensure `main.py` imports any other Python files in your program.

      - name: Upload executable
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-ytmusic-sync
          path: dist/ytmusic-sync*
